# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build, tag, and push docker image to DockerHub
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        REPOSITORY: ${{ secrets.DOCKERHUB_REPO_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo $PASSWORD | docker login -u $USERNAME --password-stdin
        docker build -t $REPOSITORY:$IMAGE_TAG .
        docker push $REPOSITORY:$IMAGE_TAG
